mutation CreatePackage(
  $nama_paket: String!
  $kategori: String!
  $harga_dasar: Int!
  $durasi_menit: Int!
  $maks_orang: Int!
  $deskripsi: String!
  $isPopular: Boolean!
) @auth(level: USER) {
  package_insert(data: {
    nama_paket: $nama_paket
    kategori: $kategori
    harga_dasar: $harga_dasar
    durasi_menit: $durasi_menit
    maks_orang: $maks_orang
    deskripsi: $deskripsi
    isPopular: $isPopular
  })
}

mutation CreateSchedule(
  $tanggal: String!
  $jam_mulai: String!
  $jam_selesai: String!
  $status_slot: String!
) @auth(level: USER) {
  schedule_insert(data: {
    tanggal: $tanggal
    jam_mulai: $jam_mulai
    jam_selesai: $jam_selesai
    status_slot: $status_slot
  })
}

mutation UpdateScheduleStatus(
  $id: UUID!
  $status_slot: String!
) @auth(level: USER) {
  schedule_update(
    id: $id
    data: { status_slot: $status_slot }
  )
}

mutation DeleteSchedule($id: UUID!) @auth(level: USER) {
  schedule_delete(id: $id)
}

mutation CreateBooking(
  $kode_booking: String!
  $userId: String!
  $packageId: UUID!
  $scheduleId: UUID!
  $totalHarga: Int!
) @auth(level: USER) {
  booking_insert(data: {
    kode_booking: $kode_booking
    userId: $userId
    packageId: $packageId
    scheduleId: $scheduleId
    totalHarga: $totalHarga
    status: "pending"
  })
}
