mutation CreatePackage(
  $namaPaket: String!
  $kategori: String!
  $hargaDasar: Int!
  $durasiMenit: Int!
  $maksOrang: Int!
  $deskripsi: String!
  $isPopular: Boolean!
) @auth(level: USER) {
  package_insert(data: {
    namaPaket: $namaPaket
    kategori: $kategori
    hargaDasar: $hargaDasar
    durasiMenit: $durasiMenit
    maksOrang: $maksOrang
    deskripsi: $deskripsi
    isPopular: $isPopular
  })
}

mutation CreateSchedule(
  $tanggal: String!
  $jamMulai: String!
  $jamSelesai: String!
  $statusSlot: String!
) @auth(level: USER) {
  schedule_insert(data: {
    tanggal: $tanggal
    jamMulai: $jamMulai
    jamSelesai: $jamSelesai
    statusSlot: $statusSlot
  })
}

mutation UpdateScheduleStatus(
  $id: UUID!
  $statusSlot: String!
) @auth(level: USER) {
  schedule_update(
    id: $id
    data: { statusSlot: $statusSlot }
  )
}

mutation DeleteSchedule($id: UUID!) @auth(level: USER) {
  schedule_delete(id: $id)
}

mutation CreateBooking(
  $kodeBooking: String!
  $userId: String!
  $packageId: UUID!
  $scheduleId: UUID!
  $totalHarga: Int!
) @auth(level: USER) {
  booking_insert(data: {
    kodeBooking: $kodeBooking
    userId: $userId
    packageId: $packageId
    scheduleId: $scheduleId
    totalHarga: $totalHarga
    status: "pending"
  })
}
