query ListPackages @auth(level: PUBLIC) {
  packages {
    id
    namaPaket
    kategori
    hargaDasar
    durasiMenit
    maksOrang
    deskripsi
    isPopular
  }
}

query GetPackage($id: UUID!) @auth(level: PUBLIC) {
  package(id: $id) {
    id
    namaPaket
    kategori
    hargaDasar
    durasiMenit
    maksOrang
    deskripsi
    isPopular
  }
}

query ListAdditionalServices @auth(level: PUBLIC) {
  additionalServices {
    id
    namaLayanan
    hargaSatuan
  }
}

query ListSchedules @auth(level: PUBLIC) {
  schedules(orderBy: [{tanggal: ASC}, {jamMulai: ASC}]) {
    id
    tanggal
    jamMulai
    jamSelesai
    statusSlot
  }
}

query GetSchedulesByDate($tanggal: String!) @auth(level: PUBLIC) {
  schedules(where: {tanggal: {eq: $tanggal}}, orderBy: [{jamMulai: ASC}]) {
    id
    tanggal
    jamMulai
    jamSelesai
    statusSlot
  }
}

query ListVouchers @auth(level: PUBLIC) {
  vouchers {
    id
    kodeVoucher
    tipeDiskon
    nilaiDiskon
    tglBerlaku
    tglBerakhir
    kuota
  }
}

query CheckVoucher($kode: String!) @auth(level: PUBLIC) {
  vouchers(where: {kodeVoucher: {eq: $kode}}) {
    id
    kodeVoucher
    tipeDiskon
    nilaiDiskon
    tglBerlaku
    tglBerakhir
    kuota
  }
}
