type Package @table {
  id: UUID! @default(expr: "uuidV4()")
  namaPaket: String!
  kategori: String!
  hargaDasar: Int!
  durasiMenit: Int!
  maksOrang: Int!
  deskripsi: String!
  isPopular: Boolean! @default(value: false)
}

type AdditionalService @table {
  id: UUID! @default(expr: "uuidV4()")
  namaLayanan: String!
  hargaSatuan: Int!
}

type Schedule @table {
  id: UUID! @default(expr: "uuidV4()")
  tanggal: String!
  jamMulai: String!
  jamSelesai: String!
  statusSlot: String! @default(value: "tersedia")
}

type Voucher @table {
  id: UUID! @default(expr: "uuidV4()")
  kodeVoucher: String!
  tipeDiskon: String!
  nilaiDiskon: Int!
  tglBerlaku: String!
  tglBerakhir: String!
  kuota: Int!
}

type Booking @table {
  id: UUID! @default(expr: "uuidV4()")
  kodeBooking: String!
  userId: String!
  packageId: UUID!
  scheduleId: UUID!
  totalHarga: Int!
  status: String! @default(value: "pending")
  createdAt: Timestamp! @default(expr: "request.time")
}
